### PR TITLE
Defined Async function

### PR DESCRIPTION
**Pull request by kael-aiur**
I referenced the Python version to define the asnyc interface for handling streaming responses of AI generated content, but not I have not implement for openAI (throw NotSupportedOperationExxception), I just implement in my private llm client for preview.

### CODE REVIEW

**Comment by kael-aiur** [comment]
Is there a merge plan for this pull request?

**Comment by HamaWhiteGG** [comment]
> Is there a merge plan for this pull request?

Sorry, I was busy with a business trip recently. Could you please submit another PR? Thank you for your contribution.

**Comment by kael-aiur** [comment]
Ok, let me merge your latest updates.

**Comment by HamaWhiteGG** [comment]
> Ok, let me merge your latest updates.

ok, thanks

**Pull request closed without merging**
